### ISSUE TITLE
egg bot is drawing mirror image, not true image

### ISSUE THREAD

**Issue by jonnolen** [Makeblock-official/mDrawBot#16]
We used the superman logo and the iron man image from https://github.com/Cration/mDrawBot-resources/blob/master/Examples%20of%20material/eggbot/

The mirror imaging isn't apparent on the iron man head but the text is mirrored. Superman logo also prints reversed so it's not really an S

**Comment by Makeblock-official** [comment]
try inverse the motor in the setup menu, thanks

**Comment by jonnolen** [comment]
That worked!  Thanks.
