### ISSUE TITLE
won't load svg files with text even if the text is converted to path first

### ISSUE THREAD

**Issue by jonnolen** [Makeblock-official/mDrawBot#18]
Built an svg with inkscape, choose generic sans-serif font.

path a:
save file as plain svg.
load in mdraw
no image shows

path b:
select text
convert object to path
save as plain svg
load in mdraw
path is garbled.

both files load correctly in chrome, firefox and safari.

**Comment by Makeblock-official** [comment]
The svg router is a home brew one, maybe not support all symbols in w3c standard. Would you please upload your svg file and i will look into it.

**Comment by jonnolen** [comment]
Here is a sample file:
https://drive.google.com/file/d/0B0Ze0R5lw0KDY0lBZ19RVm9nRUE/view?usp=sharing

This is what it looks like in firefox:
![mozilla firefox 2015-06-03 18-52-22](https://cloud.githubusercontent.com/assets/617662/7973265/aae7c4a0-0a21-11e5-9eaf-74cbfc889d25.png)

this is what mdraw thinks it looks like:
![mdraw 2015-06-03 18-52-55](https://cloud.githubusercontent.com/assets/617662/7973276/beea4b30-0a21-11e5-98dc-9f2d754f2bac.png)

**Comment by robbo1** [comment]
Looking at the svg file, mDraw does not know what to do with the "q" state in the path "d" 

The letters without the "q" state rendered correctly

**Comment by jonnolen** [comment]
i'm going to attempt to dig into this and make it work.
