### ISSUE TITLE
X and Y reversed for xybot

### ISSUE THREAD

**Issue by meeuw** [Makeblock-official/mDrawBot#31]
Please have a look at this image:
https://raw.githubusercontent.com/Makeblock-official/mDrawBot/master/mDrawGui/images/xy_setup.png

From this image Y > X

and this code:
https://github.com/Makeblock-official/mDrawBot/blob/master/mDrawGui/XYRobot.py#L99

As you can see:
self.width = 380
self.height = 310

Height < Width

I think the above code is right and the image (and firmware) are now wrong.

I'll try to write a patch this week.

**Comment by MikeHg** [comment]
It's not only that xy are changed. I drew a picture with a laser and it seems that sides are also mirror-inverted. It might be that this is only a subsequent error of the bug meeuw reported.

Btw: This error does not seem to occur on the "master" version in github (mdrawbot-master)

**Comment by meeuw** [comment]
@MikeHg could you please test, obviously it works for me :-)
